name: screen_retriever_platform_interface
description: A common platform interface for the screen_retriever plugin.
version: 0.2.0
homepage: https://github.com/leanflutter/screen_retriever/blob/main/packages/screen_retriever_platform_interface

environment:
  sdk: ">=3.2.4 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.0
  mostly_reasonable_lints: ^0.1.1
